supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'current'
    - 'x86'
    - 'ia32'
  libc:
    - 'current'
    - 'glibc'
    - 'musl'
